[package]
name = "job-notif"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.14"
quick-xml = "0.38"
axum = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "gzip"] }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "macros", "migrate"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
dotenvy = "0.15"
futures-util = "0.3"
subtle = "2.6"

[profile.release]
strip = true
lto = true
codegen-units = 1
