CREATE TABLE greetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE background_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'running', 'completed')),
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE sync_state (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    last_successful_sync TIMESTAMPTZ
);
INSERT INTO sync_state (id, last_successful_sync) VALUES (1, NULL);

CREATE TABLE job_postings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    source_job_id TEXT NOT NULL,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    location TEXT,
    workplace_type TEXT,
    employment_type TEXT,
    department TEXT,
    team TEXT,
    description TEXT,
    description_text TEXT,
    posted_at TEXT,
    salary_min DOUBLE PRECISION,
    salary_max DOUBLE PRECISION,
    salary_currency TEXT,
    url TEXT NOT NULL,
    details_json TEXT NOT NULL DEFAULT '{}',
    first_seen_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    last_seen_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE(company, source, source_job_id)
);
CREATE INDEX idx_job_postings_company ON job_postings(company);
CREATE INDEX idx_job_postings_workplace ON job_postings(workplace_type);
